name: cd

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Write application.yml
        env:
          APPLICATION_YML: ${{ secrets.APPLICATION_YML }}
          APPLICATION_TEST_YML: ${{ secrets.APPLICATION_TEST_YML }}
        run: |
          echo "${APPLICATION_YML}" > my-baseball-all-star/src/main/resources/application.yml
          echo "${APPLICATION_TEST_YML}" > my-baseball-all-star/src/test/resources/application-test.yml

      - name: Upload source to artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: my-baseball-all-star

  deploy:
    needs: build
    runs-on: my-baseball-all-star-server  # self-hosted runner
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: ./my-baseball-all-star

      - name: Give execute permission for gradlew
        run: chmod +x ./my-baseball-all-star/gradlew

      - name: Build Docker image
        run: |
          cd my-baseball-all-star
          docker build --platform linux/amd64 -t my-baseball-all-star-app .

      - name: Stop and remove existing container if running
        run: |
          docker stop my-baseball-all-star-app || true
          docker rm my-baseball-all-star-app || true

      - name: Run Docker container
        run: |
          docker run -d --name my-baseball-all-star-app -p 8080:8080 my-baseball-all-star-app
